#!/usr/bin/env python3
"""Generates docs/adr/ADR-INDEX.md from every docs/adr/*.md file's
frontmatter (id, status, supersedes, superseded_by) plus its H1 title.

Build artifact only -- never hand-maintained (ADR-0036's own design,
Log4brains/MADR-style tooling precedent: the index is derived, so it
can't drift from the ADRs themselves as long as it's regenerated after
an ADR is added or edited).

Run manually, human/session-triggered -- not wired into a pre-commit/
pre-push hook. Matches this repo's own existing precedent for
generated-but-not-automatic tooling (scripts/install-hooks.sh,
scripts/sync-tooling.sh are both explicitly "human-triggered only, run
after a relevant change"), and ADR creation/editing is rare compared to
docs/BACKLOG.md/docs/ROADMAP.md churn -- doesn't carry the same "will
be forgotten" risk profile that justified automating those. Whoever
adds or edits an ADR in a session re-runs this before the session ends,
same convention as ToolTempest's MANIFEST.txt consumer obligation
(docs/CONSTITUTION.md).
"""
import re
import sys
from pathlib import Path

ADR_DIR = Path("docs/adr")
OUTPUT = ADR_DIR / "ADR-INDEX.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_RE = re.compile(r"^#\s*(?:ADR-)?\d{4}\s*[:—-]?\s*(.+)$", re.MULTILINE)
FILENUM_RE = re.compile(r"^(\d{4})-")


def parse_frontmatter(text: str) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip()
    return fm


def main():
    rows = []
    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name == "ADR-INDEX.md":
            continue
        m = FILENUM_RE.match(path.name)
        if not m:
            print(f"WARNING: skipping {path.name}, doesn't match NNNN-slug.md", file=sys.stderr)
            continue
        number = m.group(1)
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)

        title_match = H1_RE.search(text)
        title = title_match.group(1).strip() if title_match else "(no title found)"

        rows.append({
            "id": fm.get("id", f"ADR-{number}"),
            "title": title,
            "status": fm.get("status", "(no frontmatter)"),
            "supersedes": fm.get("supersedes", "null"),
            "superseded_by": fm.get("superseded_by", "null"),
            "file": path.name,
        })

    lines = [
        "# ADR Index",
        "",
        "Generated by `scripts/generate_adr_index.py` -- never hand-edit.",
        "Derived from every `docs/adr/*.md` file's YAML frontmatter, not a",
        "separately maintained record (ADR-0036, relocated to frontmatter by",
        "ADR-0040) -- re-run after adding or editing an ADR in this session,",
        "same convention as ToolTempest's `MANIFEST.txt` consumer obligation.",
        "",
        "| ID | Title | Status | Supersedes | Superseded by |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| [{r['id']}]({r['file']}) | {r['title']} | {r['status']} | "
            f"{r['supersedes']} | {r['superseded_by']} |"
        )
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: wrote {OUTPUT} ({len(rows)} ADRs indexed).")


if __name__ == "__main__":
    main()
