"""One-shot orchestration script for Strategy Layer's M5 real-data
validation run (SPEC.md Test Plan item 4, Milestone M5).

Loads the real Claim and Evidence records already used for Evidence
Package's own pilot validation (docs/ARCHITECTURE.md's Evidence
Package row), runs them through M1's join_claims_and_evidence +
run_pre_filter, M2's check_all_claims_unverifiable_gate, M3's
build_claim_treatment (with real, individually-authored Stage 2
framing decisions for any pre-filter "include" pair — see
FRAMING_DECISIONS below), and M4's build_verdict + write_outputs.

Throwaway orchestration, same class as evidence_package/driver.py: no
reusable library logic lives here, only wiring — not TDD'd for that
reason, same judgment as M4's driver-script class of code.

Source files, resolved by inspection (not assumed) this session:
- claims:   claim_extraction/output/pilot_run_20260811T165911_backfill_20260815T104306_03.json
- evidence: evidence_package/output/evidence_run_20260815T150904.json
  (the more recent of two real Evidence Package runs on this same
  5-Claim set — supersedes evidence_run_20260813T114717.json per that
  run's own log note: a context_layer-enriched search_query rerun,
  Milestone 4, which reassessed claim 20260811T165911_04 from
  "unverifiable" to "verified". docs/ARCHITECTURE.md's Evidence
  Package Validation row ("5 live Claims tested, 5/5 unverifiable")
  reflects the OLDER, pre-rerun run and is stale relative to this
  more current one — flagged, not silently corrected, in this
  script's own run output and this milestone's report.)
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import framing  # noqa: E402
import pre_filter  # noqa: E402
import write_verdict  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAIMS_PATH = (
    REPO_ROOT
    / "claim_extraction"
    / "output"
    / "pilot_run_20260811T165911_backfill_20260815T104306_03.json"
)
EVIDENCE_PATH = (
    REPO_ROOT / "evidence_package" / "output" / "evidence_run_20260815T150904.json"
)

# Real, individually-reasoned Stage 2 framing decisions (SPEC.md
# Execution Model Stage 2; framing.decide_framing()'s interactive seam)
# — authored by reading each included Claim's context and Evidence
# content directly, not generated by template. Keyed by claim_id so a
# missing entry fails loudly (see the KeyError below) rather than
# silently skipping a Claim that needs one.
FRAMING_DECISIONS = {
    "20260811T165911_04": (
        "Anchor the claim in the AdIndex.ru-reported 2024 Facebook study "
        "(posting frequency shifted 17-34%, content 4-57% by personality "
        "trait once users knew they were observed) as the concrete "
        "evidence, not the general 'observer effect' analogy the atom's "
        "own basis leaned on. Voice: cautious, not breathless — the "
        "atom's own confidence is 0.4 and every field is tagged "
        "GIPOTEZA (hypothesis). Frame the actionable point the way the "
        "source itself frames it: minimize measurement-induced "
        "distortion (longer observation windows, automated collection, "
        "minimal experimenter contact), not claim it can be eliminated "
        "— matching both the atom's own desired_action and the "
        "source's stated mitigation practice."
    ),
}


def main() -> None:
    print(f"claims source: {CLAIMS_PATH}")
    print(f"evidence source: {EVIDENCE_PATH}")

    with open(CLAIMS_PATH, "r", encoding="utf-8") as f:
        claims = json.load(f)
    with open(EVIDENCE_PATH, "r", encoding="utf-8") as f:
        evidence_records = json.load(f)

    print(f"claims loaded: {len(claims)}")
    print(f"evidence records loaded: {len(evidence_records)}")

    missing_context = [c["claim_id"] for c in claims if c.get("context") is None]
    if missing_context:
        print(f"REFUSING: Claims missing 'context': {missing_context}")
        sys.exit(1)
    print("all Claims confirmed to carry a non-null 'context' field")

    pairs = pre_filter.join_claims_and_evidence(claims, evidence_records)
    print(f"joined pairs: {len(pairs)}")

    pre_filter_results = {
        claim["claim_id"]: pre_filter.classify_pair(claim, evidence)
        for claim, evidence in pairs
    }
    for claim_id, result in pre_filter_results.items():
        print(f"  {claim_id}: pre_filter_classification={result['pre_filter_classification']}")

    gate_result = pre_filter.check_all_claims_unverifiable_gate(pairs)
    print(f"gate_result: {gate_result}")

    include_claim_ids = [
        cid
        for cid, r in pre_filter_results.items()
        if r["pre_filter_classification"] == "include"
    ]
    print(f"pre-filter 'include' pairs: {len(include_claim_ids)} -> {include_claim_ids}")
    if not include_claim_ids:
        print("zero 'include' pairs — no Stage 2 framing decisions needed for this run")

    claim_treatments = []
    for claim, evidence in pairs:
        claim_id = claim["claim_id"]
        pf = pre_filter_results[claim_id]

        if pf["pre_filter_classification"] == "include":
            if claim_id not in FRAMING_DECISIONS:
                raise KeyError(
                    f"{claim_id}: pre_filter_classification is 'include' but no "
                    f"real framing decision was authored for it in "
                    f"FRAMING_DECISIONS — this must not be silently skipped."
                )
            treatment = framing.build_claim_treatment(
                claim_id=claim_id,
                pre_filter_classification=pf["pre_filter_classification"],
                pre_filter_reason=pf["reason"],
                framing=FRAMING_DECISIONS[claim_id],
            )
        else:
            treatment = framing.build_claim_treatment(
                claim_id=claim_id,
                pre_filter_classification=pf["pre_filter_classification"],
                pre_filter_reason=pf["reason"],
            )
        claim_treatments.append(treatment)

    run_id = datetime.now(timezone.utc).astimezone().strftime("%Y%m%dT%H%M%S")
    verdict = write_verdict.build_verdict(run_id, gate_result, claim_treatments)

    print("\n=== verdict ===")
    print(json.dumps(verdict, ensure_ascii=False, indent=2))

    verdict_path = write_verdict.write_outputs(run_id, verdict)
    print(f"\nverdict written: {verdict_path}")


if __name__ == "__main__":
    main()
